services:
  app:
    build: .

    container_name: we-love-movies-app

    env_file:
      - .env

    environment:
      - NODE_ENV=production
      - PORT=5000

    expose:
      - "5000"
    networks:
      - shared_proxy
    restart: unless-stopped

networks:
  shared_proxy:
    external: true